### ISSUE TITLE
attribute en double

### ISSUE THREAD

**Issue by hacoeurethique** [Processus-Thief/Bypass-AV-DirectSyscalls#2]
Bonjour, j'ai suivi à la lettre la video https://www.youtube.com/watch?v=n5r2jc2X6lc
J'ai installé visual studio code et dotnet
je ne suis pas programmeuse mais j'essaie de suivre les pros !

La première partie a fonctionné tout de suite et j'ai pu obtenir le résultat de l'encodeur XOR
mais la deuxième partie me pose problème, voici les message d'erreurs lorsque j'ai lancé dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained true -p:PublishTrimmed=true

C:\Users\xxx\Downloads\BYPASS\obj\Release\net7.0\win-x64\BYPASS.AssemblyInfo.cs(15,12): error CS0579: Attribut 'System.Reflection.Assembly 
FileVersionAttribute' en double [C:\Users\xxx\Downloads\BYPASS\BYPASS.csproj]
C:\Users\xxx\Downloads\BYPASS\obj\Release\net7.0\win-x64\BYPASS.AssemblyInfo.cs(17,12): error CS0579: Attribut 'System.Reflection.Assembly 
ProductAttribute' en double [C:\Users\xxx\Downloads\BYPASS\BYPASS.csproj]
C:\Users\xxx\Downloads\BYPASS\obj\Release\net7.0\win-x64\BYPASS.AssemblyInfo.cs(18,12): error CS0579: Attribut 'System.Reflection.Assembly 
TitleAttribute' en double [C:\Users\xxx\Downloads\BYPASS\BYPASS.csproj]
C:\Users\xxx\Downloads\BYPASS\obj\Release\net7.0\win-x64\BYPASS.AssemblyInfo.cs(19,12): error CS0579: Attribut 'System.Reflection.Assembly 
VersionAttribute' en double [C:\Users\xxx\Downloads\BYPASS\BYPASS.csproj]
C:\Users\xxx\Downloads\BYPASS\DInvoke\ManualMap\Overload.cs(75,105): warning CS8625: Impossible de convertir un littéral ayant une valeur  
null en type référence non-nullable. [C:\Users\xxx\Downloads\BYPASS\BYPASS.csproj]
C:\Users\xxx\Downloads\BYPASS\DInvoke\ManualMap\Overload.cs(95,101): warning CS8625: Impossible de convertir un littéral ayant une valeur  
null en type référence non-nullable. [C:\Users\xxx\Downloads\BYPASS\BYPASS.csproj]

Aucun exe généré malheureusement. j'ai besoin d'aide !
Mon unique but est de faire une démo à un client d'attaque via du phishing et des conséquences potentielles d'un téléchargement d'un fichier sur un endpoint windows
il y aura un EDR à l'affut et ce serait bien que l'antivirus ou bitdefender ne le détecte pas mais que l'EDR le détecte... enfin c'est l'idée !
Merci de votre aide
 

EDIT : j'ai trouvé comment corriger ce problème : mettre en commentaire toutes les lignes des fichiers 
C:\Users\xxx\Downloads\BYPASS\obj\Release\net7.0\win-x64\BYPASS.AssemblyInfo.cs
et
C:\Users\fpasselergue\Downloads\BYPASS\obj\Debug\net7.0\win-x64\BYPASS.AssemblyInfo.cs

on obtient bien un EXE

par contre, il est détecté par avast (version gratuite de avast) , par outlook mais pas avira
dans le cas ou il n'est pas détecté il fonctionne très bien comme indiqué dans la vidéo
mais il est malheureusement détecté par bitdefender sur windows 10 entreprise et ce, même avec plus de 500 sessions créées

**Comment by ProcessusT** [comment]
Hello :)
Désolé, je n'ai pas vérifié les issues ce weekend... Tu peux tester ce projet si tu veux quelque chose de non détecté : https://github.com/Processus-Thief/CobaltStrikeBypassDefender

Essaye avec metasploit et désactive le chargement de la librairie stdapi dans les options avancées ;)

**Comment by hacoeurethique** [comment]
Oh ! Merci de ta réponse !
Je vais tester tout ceci maintenant !

Florence

   HaCoeur Ethique
[cid:3f1fbfcc-e68c-4f31-9de8-3803dcfbfd42]
    ***@***.***
    +33 7 66 49 93 10
    https://hacoeurethique.fr

    [https://www.linkedin.com/in/florence-bauquerey-63026316a/] <https://www.linkedin.com/in/florence-bauquerey-63026316a/>
________________________________
De : Processus Thief ***@***.***>
Envoyé : mardi 31 janvier 2023 09:10
À : Processus-Thief/Bypass-AV-DirectSyscalls ***@***.***>
Cc : hacoeurethique ***@***.***>; Author ***@***.***>
Objet : Re: [Processus-Thief/Bypass-AV-DirectSyscalls] attribute en double (Issue #2)


Hello :)
Désolé, je n'ai pas vérifié les issues ce weekend... Tu peux tester ce projet si tu veux quelque chose de non détecté : https://github.com/Processus-Thief/CobaltStrikeBypassDefender<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProcessus-Thief%2FCobaltStrikeBypassDefender&data=05%7C01%7C%7C8d07d5adf7004f4d8c9d08db0362b045%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107494629977663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SfV%2FkkTqgQuUrBnu1uWpoixoMqZ6aYZ40YoD1jQKiRs%3D&reserved=0>

Essaye avec metasploit et désactive le chargement de la librairie stdapi dans les options avancées ;)
